apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3
  # Selector for finding set of Pod objects
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      # Assign a label to the Deployment object so that it can be found by a ClusterIP service
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: twci/multi-server
          ports:
            - containerPort: 5000
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: '6379'
            - name: PGUSER
              value: postgres
            - name: PGHOST
              value: postgres-cluster-ip-service
            - name: PGPORT
              value: '5432'
            - name: PGDATABASE
              value: postgres
            - name: PGPASSWORD # password gets read from secret
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD
